[tool.poetry]
name = "picasso"
version = "0.2.7"
description = ""
authors = ["Florian Keruzore <fkeruzore@anl.gov>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
numpy = "^1.25.2"
scipy = "^1.11.2"
h5py = "^3.9.0"
astropy = "^5.3.3"

[tool.poetry.group.data_helpers]
optional = true

[tool.poetry.group.data_helpers.dependencies]
pygio = {git = "https://git.cels.anl.gov/hacc/genericio.git"}
matplotlib = "^3.8.1"

[tool.poetry.group.tests]
optional = true

[tool.poetry.group.tests.dependencies]
pytest = "^7.4.2"
pytest-benchmark = "^4.0.0"

[tool.poetry.group.dev]
optional = true

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.2"
flake8 = "^6.1.0"
black = "^23.10.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "--benchmark-disable -ra -q --benchmark-group-by=func"
testpaths = [
    "tests",
]