[tool.poetry]
name = "picasso"
version = "0.1.0"
description = ""
authors = ["Florian Keruzore <fkeruzore@anl.gov>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.13"
jax = "0.4.11"
numpy = "^1.25.2"
scipy = "^1.11.2"
h5py = "^3.9.0"
astropy = "^5.3.3"

[tool.poetry.group.test.dependencies]
pytest = "^7.4.2"
halotools = "^0.8.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
